CREATE USER C##BDBLHW IDENTIFIED BY mypass;
GRANT CONNECT TO C##BDBLHW;
GRANT CREATE SESSION,GRANT ANY PRIVILEGE TO C##BDBLHW;
GRANT UNLIMITED TABLESPACE TO C##BDBLHW;
GRANT CREATE TABLE TO C##BDBLHW;
